#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS  ]]; then
    STOW_FOLDERS="nvim,git,zsh,i3,alacritty"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/Work/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
