[class]
image_default = [
    { command = "qimgv", fork = true, silent = true },
    { command = "krita", fork = true, silent = true }
]

video_default = [
    { command = "mpv" }
]

all_default = [
    { command = "xdg-open" }
]

[extension]
## Image Type
png.inherit  = "image_default"
jpg.inherit  = "image_default"
jpeg.inherit = "image_default"
webp.inherit = "image_default"

## Video Type
mkv.inherit  = "video_default"
mp4.inherit  = "video_default"
ts.inherit   = "video_default"
webm.inherit = "video_default"

## Epub Type
epub.inherit = "all_default"

[mimetype]

# text/*
[mimetype.text]
inherit = "text_default"

# application/octet-stream
[mimetype.application.subtype.octet-stream]
inherit = "video_default"
